name: Auto Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
          
            echo "‚¨áÔ∏è Pull latest backend code"
            cd ~/leadway_gas/lpg-gas-backend
            git pull origin main
          
            echo "üì¶ Backend install"
            npm install --production
          
            echo "‚ôªÔ∏è Reload backend"
            pm2 reload lpg-gas-backend
          
            echo "‚¨áÔ∏è Pull latest frontend code"
            cd ../lpg-gas-admin-agency
            git pull origin main
          
            echo "üì¶ Frontend install & build"
            npm install
            npm run build
          
            echo "‚ôªÔ∏è Reload frontend"
            pm2 reload lpg-gas-admin
          
            pm2 save
